const supabaseAnonkey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieGFpb2dxcnloYXR0ZmFtY2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTk0MDIsImV4cCI6MjA2NzIzNTQwMn0.S9m8NDEdmxejbr6KOkqpKZIMtDd8dB7yATDQwADSS8M";
const supaBaseUrl = "https://abxaiogqryhattfamcho.supabase.co";
